from .MenuBlockFR import MBlock
from .RestWindow import Resta
from .stdINPbx import Mes
from .stdYAYbx import yay
from .TilLoader import MakTil
from .ButtonMaster import buiton
from .InfoBox import infbox
from .MrCanMan import Buddon,Keys
from .TilLoader import MakTil
from .MenuBox import MenuBox